name: Continuous Integration and Delivery

on: 
  push:
    branches: [main]

env:
  GITHUB_IMAGE: ghcr.io/andrasnagy-data/django-tdd-docker/drf

jobs:

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get version tag from pyproject.toml
        uses: SebRollen/toml-action@v1.0.2
        id: read_toml
        with:
          file: pyproject.toml
          field: tool.poetry.version
      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          pull: true
          push: true
          cache-from: ${{ env.GITHUB_IMAGE }}:${{ steps.read_toml.outputs.value }}
          tags: ${{ env.GITHUB_IMAGE }}:${{ steps.read_toml.outputs.value }}
          file: ./app/Dockerfile.prod

  test:
    name: Test Docker Image
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get version tag from pyproject.toml
        uses: SebRollen/toml-action@v1.0.2
        id: read_toml
        with:
          file: pyproject.toml
          field: tool.poetry.version
      - name: Build image
        run: |
          docker build \
            --cache-from ${{ env.IMAGE }}:${{ steps.read_toml.outputs.value }} \
            --tag ${{ env.IMAGE }}:${{ steps.read_toml.outputs.value }} \
            --file ./app/Dockerfile.prod \
            "."
      - name: Run container
        run: |
          docker run \
            -d \
            --name django-tdd \
            ${{ env.IMAGE }}:${{ steps.read_toml.outputs.value }}
      - name: Pytest
        run: docker exec django-tdd python -m pytest .
      - name: Flake8
        run: docker exec django-tdd python -m flake8 .
      - name: Black
        run: docker exec django-tdd python -m black . --check
      - name: isort
        run: docker exec django-tdd python -m isort . --check-only


  # deploy:
  #   name: Deploy to Heroku
  #   runs-on: ubuntu-latest
  #   needs: [build, test]
  #   env:
  #     HEROKU_APP_NAME: nameless-atoll-80952
  #     HEROKU_REGISTRY_IMAGE: registry.heroku.com/${HEROKU_APP_NAME}/web
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         ref: main
  #     - name: Log in to GitHub Packages
  #       run: echo ${GITHUB_TOKEN} | docker login -u ${GITHUB_ACTOR} --password-stdin ghcr.io
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #     - name: Get version tag from pyproject.toml
  #       uses: SebRollen/toml-action@v1.0.2
  #       id: read_toml
  #       with:
  #         file: pyproject.toml
  #         field: tool.poetry.version
  #     - name: Pull image
  #       run: |
  #         docker pull ${{ env.IMAGE }}:${{ steps.read_toml.outputs.value }} || true
  #     - name: Build image
  #       run: |
  #         docker build \
  #           --cache-from ${{ env.IMAGE }}:${{ steps.read_toml.outputs.value }} \
  #           --tag ${{ env.HEROKU_REGISTRY_IMAGE }} \
  #           --file ./app/Dockerfile.prod \
  #           "."
  #     - name: Log in to the Heroku Container Registry
  #       run: docker login -u _ -p ${HEROKU_AUTH_TOKEN} registry.heroku.com
  #       env:
  #         HEROKU_AUTH_TOKEN: ${{ secrets.HEROKU_AUTH_TOKEN }}
  #     - name: Push to the registry
  #       run: docker push ${{ env.HEROKU_REGISTRY_IMAGE }}
  #     - name: Set environment variables
  #       run: |
  #         echo "HEROKU_REGISTRY_IMAGE=${{ env.HEROKU_REGISTRY_IMAGE }}" >> $GITHUB_ENV
  #         echo "HEROKU_AUTH_TOKEN=${{ secrets.HEROKU_AUTH_TOKEN }}" >> $GITHUB_ENV
  #     - name: Release
  #       run: |
  #         chmod +x ./release.sh
  #         ./release.sh